Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -82,6 +82,18 @@ jobs:
         run: |
           docker run -e HTTPS_PROXY=$PROXY -e HTTP_PROXY=$PROXY -e SOCKS5_PROXY=$PROXY -e NO_PROXY=$no_proxy --memory="4g" $docker_image > $log_file_name &
           DOCKER_PID=$!
+          
+          # Monitoring loop
+          while true; do
+            sleep 60 # Check every minute
+            if ! curl -s --proxy $PROXY https://www.google.com -o /dev/null; then
+              echo "Proxy failed, stopping runner and Docker container..."
+              kill $DOCKER_PID
+              exit 1
+            fi
+          done &
+          MONITOR_PID=$!
+
           sleep 16800 # Sleep for 280 minutes
           if ps -p $DOCKER_PID > /dev/null; then
             echo "Docker container running for more than 280 minutes, waiting for 10 more minutes to send logs..."
@@ -93,6 +105,7 @@ jobs:
             fi
           fi
           wait $DOCKER_PID
+          kill $MONITOR_PID
 
       - name: Send final logs to Discord
         run: |
